### ISSUE TITLE
Ads causing parts of the website to vanish

### ISSUE THREAD

**Issue by FemboyNova** [AngarosGamer/AngarosWebsite#16]
**Describe the bug**
When on the main/home page at certain sizes the ads can completly get rid of the home, cli, salad mobile, richPresence buttons

**To Reproduce**
1. Go to 'https://angaros.vercel.app/'
2: resize the page as for me on a 3440x1440 it hides the icons when i put it to half the size of the screen
3. See error

**Expected behavior**
For adverts to not be in the way of the buttons to cause them to disappear

**Screenshots**
[https://media.discordapp.net/attachments/975773091034714142/987837718128099419/unknown.png?width=1290&height=540](url)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 102.0.5005.115

**Comment by AngarosGamer** [comment]
t'was already the case in the older version, there just wasn't an ad. It's not that the buttons are hidden by the ad, it's that they get completely removed when the size gets decreased by some amount.
A fix for this will be made when the site revamp is made. I'll hopefully be able to start work on it within a week, and if all goes well many issues will be fixed then).
While I'm not sure how much I'll be able to implement, here's a list of issues I want to get removed / features to add:
 - Fix the index page for buttons to show
 - Allow mobile viewing (dynamic display)
 - Rework to the user flow (potentially, directing a user to a guide based on inputted hardware specs)
 - Rework to content flow (how you interact with the website content, go from point A to point B to find information
This is still very generic since I haven't given it enough thought or even started wireframing anything, but work will start either this week or the one after that.
